# Generated by Django 5.0.2 on 2025-05-14 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('HEALTH', 'Health Insurance'), ('RETIREMENT', 'Retirement Plan'), ('WELLNESS', 'Wellness Program')], max_length=20)),
                ('description', models.TextField()),
                ('available_to', models.ManyToManyField(related_name='available_benefits', to='performance.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.benefit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.userprofile')),
            ],
        ),
    ]
