# Generated by Django 5.0.2 on 2025-05-14 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_benefit_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review_date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.userprofile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='performance.userprofile')),
            ],
        ),
    ]
